### PR TITLE
Add enable damage suport

### PR DESCRIPTION
**Pull request by Emojigit**

### CODE REVIEW

**Comment by SmallJoker** [comment]
This armor group is already added automatically since 5.1.0 or so.

**Comment by Emojigit** [comment]
> This armor group is already added automatically by Minetest since 5.1.0 or so, hence is should already be possible to have per-player enabled damage without this change.
> It's a bug if this doesn't work.

I can still receive damage on a 5.3.0 server without enabling damage.

**Comment by BuckarooBanzay** [comment]
> > This armor group is already added automatically by Minetest since 5.1.0 or so, hence is should already be possible to have per-player enabled damage without this change.
> > It's a bug if this doesn't work.
> 
> I can still receive damage on a 5.3.0 server without enabling damage.

Can you file an issue then? Tthis sounds like a bug. Please also include what mods you used and what you did exactly, thanks :+1:

**Comment by Emojigit** [comment]
> > > This armor group is already added automatically by Minetest since 5.1.0 or so, hence is should already be possible to have per-player enabled damage without this change.
> > > It's a bug if this doesn't work.
> > 
> > 
> > I can still receive damage on a 5.3.0 server without enabling damage.
> 
> Can you file an issue then? This sounds like a bug. Please also include what mods you used and what you did exactly, thanks +1

I received damage when I drop (I disabled PVP so I can't receive any damage from players)

**Comment by SmallJoker** [comment]
> I received damage when I drop

Tested it right now using 5.4.0-dev (from this week) plus latest 3d_armor + shields. No falling damage is applied.

**Comment by Emojigit** [comment]
> > I received damage when I drop
> 
> Tested it right now using 5.4.0-dev (from this week) plus latest 3d_armor + shields. No falling damage is applied.

both of my server and client are 5.3.0
The server side: Linux Ubuntu 20.04 LTS x86_64
The Client: Windows 10 x86_64

**Comment by BuckarooBanzay** [comment]
> > > I received damage when I drop
> > 
> > 
> > Tested it right now using 5.4.0-dev (from this week) plus latest 3d_armor + shields. No falling damage is applied.
> 
> both of my server and client are 5.3.0
> The server side: Linux Ubuntu 20.04 LTS x86_64
> The Client: Windows 10 x86_64

mods?

**Comment by Emojigit** [comment]
> > > > I received damage when I drop
> > > 
> > > 
> > > Tested it right now using 5.4.0-dev (from this week) plus latest 3d_armor + shields. No falling damage is applied.
> > 
> > 
> > both of my server and client are 5.3.0
> > The server side: Linux Ubuntu 20.04 LTS x86_64
> > The Client: Windows 10 x86_64
> 
> mods?

This is the mod list.

> 3d_armor, 3d_armor_sfinv, 3d_armor_stand, 3d_armor_ui, advtrains, advtrains_interlocking, advtrains_line_automation, advtrains_luaautomation, advtrains_platform, advtrains_signals_ks, advtrains_train_industrial, advtrains_train_japan, advtrains_train_steam, advtrains_train_subway, advtrains_train_track, airtanks, anti_lava_area, antishroom, apartment, areas, areas_pay, assets, atchat, atm, bakedclay, bale, balloonblocks, ban_hacker, banish, banners, barrier, basic_houses, basic_materials, basic_robot, beacons, beds, better_fences, binoculars, biome_lib, block_in_block, boards, boats, bonemeal, bones, books, bouncy_bed, bows, brick_furnace, bridger, bucket, bucket_wooden, building_blocks, builtin_item, butterflies, c_doors, cake, canned_food, cannons, carts, castle_farming, castle_gates, castle_lighting, castle_masonry, castle_shields, castle_storage, castle_tapestries, castle_weapons, cblocks, ccserver_guide, character_creator, chat_record, computer, concrete, cottages, crafting_bench, creative, currency, death_messages, default, digiboard, digiline_remote, digiline_terminal, digilines, digilines_crafting, digilines_memory, digilines_weather_sensor, digiprinter, digtron, disable_rc, disco_trains, discordmt_pvp, display_api, doors, drawers, dungeon_loot, dye, ehlphabet, elevator, emoji, enchanting, engrave, env_sounds, ethereal, extra_doors, extranodes, fake_fire, farebox, farming, farming_nextgen, feedlot, filter, fire, fireflies, fireworkz, flowers, font_api, font_metro, food, food_basic, freezer, function_delayer, game_commands, get_mod_log, getter, give_initial_stuff, groundline, ham_radio, handle_schematics, hbarmor, hbhunger, heads, hidden_chests, homedecor_3d_extras, homedecor_bathroom, homedecor_bedroom, homedecor_books, homedecor_climate_control, homedecor_clocks, homedecor_cobweb, homedecor_common, homedecor_doors_and_gates, homedecor_electrical, homedecor_electronics, homedecor_exterior, homedecor_fences, homedecor_foyer, homedecor_furniture, homedecor_furniture_medieval, homedecor_gastronomy, homedecor_kitchen, homedecor_laundry, homedecor_lighting, homedecor_misc, homedecor_office, homedecor_pictures_and_paintings, homedecor_plastic, homedecor_roofing, homedecor_seating, homedecor_tables, homedecor_trash_cans, homedecor_wardrobe, homedecor_windows_and_treatments, hot_air_balloons, hp20, hudbars, ilights, illumination, inbox, init_message, itemframes, jeans_economy, kicktools, know_where_you_die, laptop, laptop_pc1, lava_n_water, lavalamp, lavastuff, linetrack, locked_travelnet, locks, lrfurn, lucky_block, mail, mailbox, map, maple, maptools, mcl_chests, mcl_util, memorandum, mesecons, mesecons_alias, mesecons_blinkyplant, mesecons_button, mesecons_commandblock, mesecons_delayer, mesecons_detector, mesecons_doors, mesecons_extrawires, mesecons_fpga, mesecons_gates, mesecons_hydroturbine, mesecons_insulated, mesecons_lamp, mesecons_lightstone, mesecons_luacontroller, mesecons_materials, mesecons_microcontroller, mesecons_movestones, mesecons_mvps, mesecons_noteblock, mesecons_pistons, mesecons_powerblock, mesecons_powerplant, mesecons_pressureplates, mesecons_random, mesecons_receiver, mesecons_solarpanel, mesecons_stickyblocks, mesecons_switch, mesecons_torch, mesecons_walllever, mesecons_window, mesecons_wires, metrosigns, mob_horse, mobf_trader, mobkit, mobs, mobs_animal, mobs_crocs, mobs_fish, mobs_jellyfish, mobs_npc, mobs_sharks, mobs_turtles, modlib, modutil, mokapi, more_mese_post_light, moreblocks, morelights, morelights_extras, morelights_modern, morelights_vintage, moremesecons_adjustable_blinkyplant, moremesecons_adjustable_player_detector, moremesecons_commandblock, moremesecons_conductor_signalchanger, moremesecons_dual_delayer, moremesecons_entity_detector, moremesecons_igniter, moremesecons_induction_transmitter, moremesecons_injector_controller, moremesecons_jammer, moremesecons_luablock, moremesecons_luacontroller_tool, moremesecons_mesechest, moremesecons_sayer, moremesecons_signalchanger, moremesecons_switchtorch, moremesecons_teleporter, moremesecons_timegate, moremesecons_utils, moremesecons_wireless, moreores, moresigns, moretrains_basic, moretrains_industrial, moretrains_japan, moretrains_steam, moretrains_vintage, moretrees, multihome, mymillwork, nnsay, notices, ontime_clocks, orbs_of_time, overpowered, painted_3d_armor, pathv7, pencil_redo, petz, pipeworks, place_node, plasmascreen, player_api, pos_marker, pvp_spawn, quartz, reportlist, rgblightstone, ropes, screwdriver, scuba, server_flags, server_news, serversay, sethome, sfinv, shields, signs, signs_api, signs_lib, signs_road, simple_streetlights, skinsdb, smartshop, smod_colored_chat, snow, space, space_moon, space_planets, spacesuit, spawn, spectator_mode, stained_glass, stairs, stairsplus, steles, str_helpers, streets, stuff_generator, technic, technic_chests, technic_cnc, technic_cnc_improve, technic_grass_clean, technic_hv_extend, technic_lamp, technic_sawmill, technic_solar_furnace, technic_worldgen, teleport_potion, textline, titanium, tnt, toolranks, towercrane, tpr, trainblocks, trampoline, trash_can, travelnet, ts_workshop, unified_inventory, unified_inventory_plus, unifieddyes, unknown_item, unknownnode, vehicles, vessels, visable_air, walls, we_undo, weather, wieldview, wiki, windmill, wine, witches, wool, worldedit, worldedit_brush, worldedit_commands, worldedit_gui, worldedit_shortcommands, wrench, xban2, xdecor, xpanes

**Comment by BuckarooBanzay** [comment]
As @SmallJoker said:

> Please disable all mods and re-enable them incrementally to figure out the real source of this bug.

I'm closing this, as it is not really clear what the actual issue is :shrug:

**Pull request closed without merging**
