### PR TITLE
Fix not being able to place armor on anvil

### PR DESCRIPTION
**Pull request by OgelGames**

### CODE REVIEW

**Review by Panquesito7 — APPROVED** [review]

**Comment by SmallJoker** [comment]
Placing armor to equip it seems to be a feature when you're in a rush (PvP arena or so).
What do you think about this approach:
 * if the pointed node has a `on_rightclick` callback -> call it
 * if the pointed node has no `on_rightclick` or "Sneak" is pressed -> equip armor

That's a common practice to switch between actions for tools that can also be put into chests directly.

**Comment by OgelGames** [comment]
@SmallJoker I didn't think it was necessary to have a check for `on_rightclick`, but now that I think of it, it makes sense for equipping armor in a confined space where you can't not point at a node.

**Review by SmallJoker — APPROVED** [review]
Works

**Comment by BuckarooBanzay** [comment]
> Works. Will merge in a few days unless there are objections.

LGTM too, i think i'm merging this right now, don't see an issue with it :yum:

**Pull request merged**
