### PR TITLE
Add Technic Armor

### PR DESCRIPTION
**Pull request by AntumDeluge**
Adds [stujones11's technic_armor](https://github.com/stujones11/technic_armor) to modpack.

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
is there a reason and/or benefit of packaging that into the base-modpack?

**Comment by AntumDeluge** [comment]
No, just more armors from the original author of the 3d_armor modpack. Thought it would be easier to keep updated if it were packaged together.

**Comment by AntumDeluge** [comment]
I won't be offended if this doesn't get accepted 🙂. I keep my own forks anyway. Just saw that the original technic_armor wasn't being maintained. So thought it would be easier to do combined with this one since they came from the same author anyway & was created as an extension of it.

**Comment by BuckarooBanzay** [comment]
> Just saw that the original technic_armor wasn't being maintained.

IMO: forking the technic_armor mod to `minetest-mods` would be the best option

**Pull request closed without merging**
