### PR TITLE
Add Support for Generating HTML Documentation with LDoc

### PR DESCRIPTION
**Pull request by AntumDeluge**
Adds HTML documentation generation using [LDoc](https://stevedonovan.github.io/ldoc/).

Live preview available [here](https://antummt.github.io/mp-3d_armor/reference/).

## File explanation:

- `gendoc.sh`: Script for automating `ldoc` invocation (not needed for using [workflow](https://github.com/AntumMT/mp-3d_armor/blob/345368e/.github/workflows/reference.yml#L28)).
- `.ldoc/config.ld`: Configuration read by LDoc.
- `.ldoc/parse_src.py`: Script for generating temporary files to create topics for each item type.
  - An alternative to this is to separate equipment types into individual scripts or use multiple `@topic` calls in `armor.lua` using the `--multimodule` command line switch ([PR 355](https://github.com/lunarmodules/LDoc/pull/355))
- `.ldoc/parse_settings.py`: Script for generating a temporary file from `settingtypes.txt` that is LDoc readable.
- `.ldoc/parse_crafts.py`: Script for generating temporary file for crafting topic.

### Workflow:

A GitHub workflow is configured to generate documentation & deploy on the `gh-pages` branch when there is a push to `master`.

### Manual:

To manually generate documentation, execute shell script `gendoc.sh` in the modpack root directory.

```sh
$ cd <3d_armor_dir>
$ ./gendoc.sh
```

By default, documentation files are exported to `3d_armor/docs/reference`. This can be changed by setting `export_dir` environment variable:

```sh
$ export_dir="custom/path" ./gendoc.sh
```

## Notes:
- The `gendoc.sh` script can be executed from any directory.
- The documentation generation currently depends on a [custom LDoc branch](https://github.com/AntumDeluge/LDoc/tree/custom). There are some upstream PRs that would make it compatible with the head branch:
  - [355](https://github.com/lunarmodules/LDoc/pull/355)
  - [359](https://github.com/lunarmodules/LDoc/pull/359)
- Because of limitations of current LDoc, I am using Python scripts to create some intermediate files for parsing & generating docs.
- ***HACKS:***
  - LDoc is trimming "shields:" from shield item names (ex: "shields:shield_wood" is being changed to "shield_wood") for unknown reasons. `config.ld` is [configured to re-add "shields:" prefix](https://github.com/AntumMT/mp-3d_armor/blob/c95553a/.ldoc/config.ld#L278).

## TODO:

- [x] add parameter data types:
  - [x] `hitter` from [armor:punch](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:punch) *(ObjectRef?)*
  - [x] `player` & `index` from [armor:run_callbacks](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:run_callbacks) *(ObjectRef, int?)*
  - [x] `armor_element` from [armor:unequip](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:unequip) *(string?)*
  - [x] `preview` from [armor:add_preview](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:add_preview)
  - [x] `item_name` from [armor:get_element](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:get_element) *(string?)*
- [x] add parameter descriptions:
  - [x] `base` from [armor:register_armor_group](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:register_armor_group)
  - [x] `index` & `stack` from [armor:damage](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:damage)
  - [x] `preview` from [armor:add_preview](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:add_preview)
  - [x] `name` & `listring` from [armor:get_armor_formspec](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:get_armor_formspec)
  - [x] `list` from [armor:serialize_inventory_list](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:serialize_inventory_list)
  - [x] `list_string` from [armor:deserialize_inventory_list](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:deserialize_inventory_list)
  - [x] `msg` from [armor:get_valid_player](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:get_valid_player)
- [x] add details to [ArmorDef](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#ArmorDef)
- [x] document registered armors in `3d_armor/armor.lua`
- [x] document registered shields in `shields/init.lua`
- [x] document craft recipes
- [x] document remaining settings
- [x] put equipment types under their own topic, or put shields under "armor" (dependent on [PR 355](https://github.com/lunarmodules/LDoc/pull/355) or generating temp file for LDoc to read)
- [x] put craft recipes under separate topic (dependent on [PR 355](https://github.com/lunarmodules/LDoc/pull/355) or generating temp file for LDoc to read)
- [x] fix build checks
  - [x] luacheck
  - [x] integration-test (either move "docs" directory or figure out how to exclude it from the Minetest execution)
- [x] delete temporary `3d_armor/docs/settings.luadoc` after HTML docs generated
- [x] remove unused parts of `config.ld`
- [x] use a more general `custom_see_handler` function (I'm not good with regular expressions)
- [x] use workflow to build docs on `gh-pages` branch
- [x] fix inventory image links
- [x] squash commits

Closes: #54

### CODE REVIEW

**Comment by AntumDeluge** [comment]
@SmallJoker, @BuckarooBanzay, if you have suggestions, I would like to hear them.

**Comment by BuckarooBanzay** [comment]
Wow, the docs look awesome :+1: i like the included items and settings

Just two questions:
* does it need your `ldoc` fork? (i see the `LDoc 1.4.6-antum-dev` in the footer)
* can we exclude the generated html-docs from the `master` branch and instead use a workflow to include them in the `gh-pages` branch? (not sure if you just did this here to show progress)

**Comment by AntumDeluge** [comment]
does it need your `ldoc` fork?
At the moment, yes. But I have put in a [PR upstream](https://github.com/lunarmodules/LDoc/pull/359) to allow using Lua built-in objects & functions. If it doesn't get accepted, I would try to find some kind of workaround so main branch can be used, hopefully.

    can we exclude the generated html-docs from the `master` branch and instead use a workflow to include them in the `gh-pages` branch?
I am new to GitHub workflows, so you probably know better than I do. But I imagine it is possible. Will a workflow allow the docs to be generated on the `gh-pages` branch?

**Comment by BuckarooBanzay** [comment]
> I am new to GitHub workflows, so you probably know better than I do. But I imagine it is possible. Will a workflow allow the docs to be generated on the gh-pages branch?

no pressure, i've done that on some other repos and can do it here afterwards :+1:

**Comment by AntumDeluge** [comment]
@SmallJoker or @BuckarooBanzay: A couple questions:

1. Is `armor_element` parameter of [armor:unequip](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:unequip) a string? ([code](https://github.com/minetest-mods/3d_armor/blob/ac76152/3d_armor/api.lua#L503))
2. What is a good description for `base` parameter of [armor:register_armor_group](https://antummt.github.io/mp-3d_armor/3d_armor/docs/reference/topics/api.html#armor:register_armor_group)? ([code](https://github.com/minetest-mods/3d_armor/blob/ac76152/3d_armor/api.lua#L135))

**Comment by AntumDeluge** [comment]
This is ready for review. But it does require [my fork of LDoc](https://github.com/AntumDeluge/ldoc/tree/custom). And I think it will take some tweaking to get it to build with a GitHub workflow. The `gendoc.sh` script depends on `ldoc` command being in the PATH.

**Comment by AntumDeluge** [comment]
Oooh, I figured out how deploy on `gh-pages` branch using workflow. 🙂

**Comment by AntumDeluge** [comment]
Forgot to change image links when I changed to building in `gh-pages` branch.

TODO:
- [ ] update image links

**Comment by AntumDeluge** [comment]
The only thing I would like better would be if the navigation panel wasn't static & didn't scroll with the rest of the page. I think maybe it can be done in CSS, but I'm not sure how.

**Comment by BuckarooBanzay** [comment]
A bit hard to test locally with all those github-links but it looks good :+1: 
Also: `leafo/gh-actions-luarocks@v4` is new to me, i think this will help me somewhere else where i did that manually in a workflow

**Comment by AntumDeluge** [comment]
> A bit hard to test locally with all those github-links

You mean the links to images? Perhaps it would be better to copy the images to the `gh-pages` branch so they can be linked locally?

**Comment by BuckarooBanzay** [comment]
> Perhaps it would be better to copy the images to the gh-pages branch

Nah, thats ok how it is currently, copying it would result in redundant files (although git would handle that properly :thinking:)

**Comment by AntumDeluge** [comment]
@BuckarooBanzay #60 actually does change it to copy images to gh-pages branch.

**Comment by BuckarooBanzay** [comment]
Yeah i saw :laughing:
I checked the repos i used my `mtinfo` mod on (it creates a static page with recipe infos) and i'm copying the textures there too to the `gh-pages` branch and it looks like git handles that pretty well :+1: (https://github.com/mt-mods/technic / https://mt-mods.github.io/technic/#/mods/technic/items)

**Pull request merged**
