### PR TITLE
Adding full license files to each mod

### PR DESCRIPTION
**Pull request by dacmot**
LGPL recommends distributing the full license text with the work. CC doesn't seem to care as much, but might as well.

This PR adds the full lgpl2.1 and cc-by-sa-3.0 text in each mod. Since this is a modpack, and therefore each mod could stand on it's own, each mod should have its own copies of the licenses.

### CODE REVIEW

**Comment by appgurueu** [comment]
Unless this is strictly necessary, this is a change for the worse. A "recommendation" alone doesn't weigh enough IMO. And even then, the "recommendation" need not be interpreted that way:

> LGPL recommends distributing the full license text with the work.

This modpack *is* the work. If someone chooses to extract mods, files or code snippets from here, the onus to preserve the license is *on them*.

**Comment by dacmot** [comment]
IANAL, so I'll let you be the judge:

> You should have received a copy of the GNU Lesser General Public License along
> with this program; if not, write to the Free Software Foundation, Inc.,
> 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

As with the modpack, then why not remove the individual `LICENSE.txt` files in each mod? If you would prefer that, I can do it. I still think it would be a good idea to at least include the full two licenses in the root of the modpack.

**Comment by Lazerbeak12345** [comment]
What if we send them a PR for both approaches? If they merge one we could close the other. I personally prefer just keeping the full text in the project root.

**Comment by BuckarooBanzay** [comment]
closing this in favor of #122 thanks again

feel free to open an issue next time for feedback :+1:

**Pull request closed without merging**
