### PR TITLE
Refactor armors to be mods rather than hardcoded into API

### PR DESCRIPTION
**Pull request by Crystalwarrior**
"armors as modpack" refactor letting anyone to enable/disable any armors they want as mods rather than obscure settings.

Settings are very out-of-the-way and hard to find, and having armors introduced inside the API itself rather than the API being clean is not the best, especially due to the MTG dependencies. This refactor will allow 3D Armors to become mod-agnostic with the goal of preserving backwards compatibility.

This PR doesn't deprecate the settings functionality, however, in the interest of backwards compatibility.

### CODE REVIEW

**Comment by BuckarooBanzay** [comment]
there are quite a few new `luacheck` errors: https://github.com/minetest-mods/3d_armor/runs/8071051369?check_suite_focus=true

give me some time to review this, it's quite a big change :thinking:

**Comment by Crystalwarrior** [comment]
@BuckarooBanzay No problem! Seems to be warnings, not sure how to resolve them.

**Comment by Crystalwarrior** [comment]
Fixed deleting brazil 😳

**Review by BuckarooBanzay — APPROVED** [review]

**Comment by BuckarooBanzay** [comment]
code looks good, license files are where they should be, everything works as before :+1: 

I'm unsure though if the `ldoc` reference will work like that (don't feel like running that locally) maybe @AntumDeluge can take a quick look at this and give some feedback (if you have some spare time)

**Comment by SmallJoker** [comment]
I like the idea, however adding new mods silently breaks the server configuration. New mods will not be loaded until they're added to `world.mt`. A less drastic change would be to move the registrations into separate files, rather than entirely new mods.

This is just my two cents of concern, however it's not a disapproval.

**Comment by AntumDeluge** [comment]
> I'm unsure though if the ldoc reference will work like that

The LDoc helper scripts will need to be updated. I'm a bit out of practice. But if this is good for the mod, I would say go ahead & make the changes & worry about updating LDoc afterwards.

**Comment by AntumDeluge** [comment]
After testing locally, the only things that it appears to break in the LDoc reference are the craft recipes & a few icon locations. It shouldn't be too hard to fix. I'll try to get it done & create a PR that can be added after this is merged.

**Comment by Crystalwarrior** [comment]
OK! 👍

**Comment by BuckarooBanzay** [comment]
> I like the idea, however adding new mods silently breaks the server configuration. New mods will not be loaded until they're added to world.mt. A less drastic change would be to move the registrations into separate files, rather than entirely new mods.

Noted, but i still think it is better in the long-term if the codebase ad textures are less intertwined. I would even go a step further and separate it into different repositories, that would break backward-compat completely though...

> The LDoc helper scripts will need to be updated. I'm a bit out of practice. But if this is good for the mod, I would say go ahead & make the changes & worry about updating LDoc afterwards.

Thanks for the review and PR's, will look into it some other day though :+1:

**Comment by Crystalwarrior** [comment]
Next target: shields 😉

**Pull request merged**
